backend:
  name: github
  repo: RostislavKor/test-gatsby-cms

media_folder: static/assets
public_folder: assets

collections:
  - name: pages
    label: pages
    folder: pages
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
